aws-task-2
AlexanderFraltsov/nodejs-aws-fe pull request #1
Opened 2020-10-20 19:23 UTC by AlexanderFraltsov

d2e067t5qk38bl.cloudfront.net

2020-10-26 14:51 UTC, NikaOrl requested changes
Please, follow convention for PR description: https://docs.rs.school/#/stage2?id=Требования-к-pull-request-pr

Score: 5/5

2020-10-26 14:51 UTC, NikaOrl commented on .gitignore
> +
A bit strange change)

2020-10-27 13:41 UTC, balasphilip approved these changes

2020-10-27 13:41 UTC, balasphilip commented
great job! max score from me.

2020-10-30 17:01 UTC, merged